FROM ubuntu:18.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y  python3-pip
RUN apt-get install -y  python3-numpy-dev
RUN pip3 install Jpype1

COPY test.py ./

CMD ["python3", "test.py"]
