FROM ubuntu:18.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y  python3-pip
RUN pip3 install numpy
RUN apt-get install -y git
RUN pip3 install git+https://github.com/jpype-project/jpype@v0.6.3

COPY test.py ./

CMD ["python3", "test.py"]
